nginx:
  image: nginx:latest
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /home/deploy/reverseProxy/conf:/etc/nginx/conf.d
    - /home/deploy/reverseProxy/certs:/etc/nginx/certs
    - /home/deploy/reverseProxy/htpasswd:/etc/nginx/htpasswd

dockergen:
  image: jwilder/docker-gen:latest
  restart: always
  volumes:
    - /home/deploy/reverseProxy/templates:/etc/docker-gen/templates
    - /var/run/docker.sock:/tmp/docker.sock:ro
  volumes_from:
    - nginx
  tty: true
  environment:
    - DEFAULT_HOST=$DEFAULT_HOST
  command: >
    -notify-sighup mainreverseproxy_nginx_1
    -watch
    -only-exposed
    /etc/docker-gen/templates/nginx.tmpl
    /etc/nginx/conf.d/default.conf
